spring.application.name=FarmSync_CropExpenseTracker


# MySQL Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/farmSync
spring.datasource.username=root
spring.datasource.password=Sayan-2736
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
