spring.application.name=farmsync
server.port=8080

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# JWT - Secure Base64 encoded key (min 256 bits)
application.security.jwt.secret-key=VGhpc0lzQVNlY3VyZVN1cGVyTG9uZ0p3dFNlY3JldEtleUZvckRlbW9QdXJwb3Nlc0luT25seQ==
application.security.jwt.expiration=86400000

# API Keys
application.security.api-keys=default-user-key:USER,default-admin-key:ADMIN