spring.application.name=farmsync
server.port=8080

# MySQL Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/farmsync_new
#spring.datasource.username=root
#spring.datasource.password=Saurabh@2006


spring.datasource.url=jdbc:mysql://localhost:3306/farmSync
spring.datasource.username=root
spring.datasource.password=Sayan-2736

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT - Secure Base64 encoded key (min 256 bits)
application.security.jwt.secret-key=VGhpc0lzQVNlY3VyZVN1cGVyTG9uZ0p3dFNlY3JldEtleUZvckRlbW9QdXJwb3Nlc0luT25seQ==
application.security.jwt.expiration=86400000

# API Keys
application.security.api-keys=default-user-key:USER,default-admin-key:ADMIN