spring.application.name=farmsync
server.port=8080

# H2 Database (temporary)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# MySQL Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/farmSync (db name)
# spring.datasource.username=
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
application.security.jwt.secret-key=YOUR_SECRET_KEY
application.security.jwt.expiration=86400000

# API Keys
application.security.api-keys=default-user-key:USER,default-admin-key:ADMIN